#include "gpio_config.h"

GPIO PA0(GPIOA, GPIO_Pin_0);
GPIO PB0(GPIOB, GPIO_Pin_0);
GPIO PC13(GPIOC, GPIO_Pin_13);
GPIO PB1(GPIOB, GPIO_Pin_1);
GPIO PH2(GPIOH, GPIO_Pin_2);
GPIO PH3(GPIOH, GPIO_Pin_3);
